const params=new URLSearchParams(location.search);const mode=params.get('mode')||document.body.dataset.defaultMode||null;const configs={public:{kicker:'Appel à projets 2026–2027',main:'Établissements publics',full:'Formulaire d’appel à projets pour établissements publics',pdf:'assets/modele-vierge.pdf'},prive:{kicker:'Appel à projets 2026–2027',main:'Établissements privés',full:'Formulaire d’appel à projets pour établissements privés',pdf:'assets/modele-vierge.pdf'},'hors-appel':{kicker:'Dépôt permanent',main:'Projet hors appel à projets',full:'Formulaire de dépôt de projet hors appel à projets',pdf:'assets/modele-vierge.pdf'}};
const config=configs[mode];document.querySelector('#modelPicker').hidden=!!config;document.querySelector('#formApp').hidden=!config;if(!config){document.title='Formulaires de dépôt — CARDIE-SEPIA Lille'}else{document.querySelector('#formKicker').textContent=config.kicker;document.querySelector('#formMainTitle').textContent=config.main;document.querySelector('#formFullTitle').textContent=config.full;document.querySelector('#blankPdf').href=config.pdf;document.title=config.full+' — CARDIE-SEPIA Lille';document.body.dataset.mode=mode;if(mode==='hors-appel')document.querySelectorAll('.hors-only').forEach(x=>x.style.display='block');if(mode!=='public')document.querySelectorAll('.public-only').forEach(x=>x.hidden=true)}
const form=document.querySelector('#projectForm');const steps=[...document.querySelectorAll('.step')];let current=0;const key=`cardie-sepia-demo-v2-${mode||'accueil'}`;
const nav=document.querySelector('#stepNav');steps.forEach((s,i)=>{const b=document.createElement('button');b.type='button';b.innerHTML=`<span>${i+1}</span>${s.dataset.title}`;b.onclick=()=>go(i);nav.appendChild(b)});
function go(i,validate=false){if(validate&&!validateStep())return;current=Math.max(0,Math.min(i,steps.length-1));steps.forEach((s,n)=>s.classList.toggle('active',n===current));[...nav.children].forEach((b,n)=>b.classList.toggle('active',n===current));document.querySelector('#stepLabel').textContent=`Étape ${current+1} sur ${steps.length}`;document.querySelector('#stepTitle').textContent=steps[current].dataset.title;document.querySelector('#progressBar').style.width=`${(current+1)/steps.length*100}%`;document.querySelector('#prevBtn').disabled=current===0;document.querySelector('#nextBtn').hidden=current===steps.length-1;window.scrollTo({top:0,behavior:'smooth'})}
function validateStep(){let ok=true;steps[current].querySelectorAll('[required]').forEach(el=>{const valid=el.type==='radio'?[...steps[current].querySelectorAll(`[name="${el.name}"]`)].some(x=>x.checked):el.value.trim();el.classList.toggle('invalid',!valid);if(!valid)ok=false});if(!ok){steps[current].querySelector('.invalid,[required]')?.focus();return false}return true}
document.querySelector('#nextBtn').onclick=()=>{save();go(current+1,true)};document.querySelector('#prevBtn').onclick=()=>go(current-1);
function data(){const out={};new FormData(form).forEach((v,k)=>{if(v instanceof File)return;if(out[k])out[k]=[].concat(out[k],v);else out[k]=v});document.querySelectorAll('.repeater').forEach(r=>{out[r.dataset.name]=[...r.querySelectorAll('.repeat-row')].map(row=>Object.fromEntries([...row.querySelectorAll('[data-field]')].map(x=>[x.dataset.field,x.value]))) });return out}
function save(){localStorage.setItem(key,JSON.stringify({savedAt:new Date().toISOString(),fields:data()}));const s=document.querySelector('#saveState');s.innerHTML='<span></span>Brouillon enregistré à '+new Date().toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'})}
function restore(){try{const saved=JSON.parse(localStorage.getItem(key)||'null');if(!saved)return;Object.entries(saved.fields||{}).forEach(([k,v])=>{if(['porteurs','partenaires'].includes(k)){restoreRepeater(k,v);return}const els=[...form.querySelectorAll(`[name="${CSS.escape(k)}"]`)];els.forEach(el=>{if(el.type==='radio'||el.type==='checkbox')el.checked=[].concat(v).includes(el.value);else el.value=Array.isArray(v)?v[0]:v})});updateConditionals()}catch(e){console.warn('Brouillon illisible',e)}}
function restoreRepeater(name,rows){const rep=document.querySelector(`.repeater[data-name="${name}"]`);if(!rep||!rows?.length)return;const box=rep.querySelector('.repeat-items'),tpl=box.firstElementChild.cloneNode(true);box.innerHTML='';rows.forEach(values=>{const row=tpl.cloneNode(true);row.querySelectorAll('[data-field]').forEach(x=>x.value=values[x.dataset.field]||'');box.appendChild(row)})}
function updateConditionals(){document.querySelectorAll('.conditional').forEach(c=>{const [name,value]=c.dataset.show.split(':');const selected=form.querySelector(`[name="${name}"]:checked`);c.classList.toggle('visible',selected?.value===value)})}
form.addEventListener('input',()=>{updateConditionals();clearTimeout(window.saveTimer);window.saveTimer=setTimeout(save,350)});form.addEventListener('change',()=>{updateConditionals();save()});
document.querySelectorAll('.repeater').forEach(rep=>{rep.querySelector('.add').onclick=()=>{const row=rep.querySelector('.repeat-row').cloneNode(true);row.querySelectorAll('input').forEach(x=>x.value='');rep.querySelector('.repeat-items').appendChild(row);save()};rep.addEventListener('click',e=>{if(!e.target.classList.contains('remove'))return;const rows=rep.querySelectorAll('.repeat-row');if(rows.length>1)e.target.closest('.repeat-row').remove();else e.target.closest('.repeat-row').querySelectorAll('input').forEach(x=>x.value='');save()})});
document.querySelector('#attachments').onchange=e=>{document.querySelector('#fileList').innerHTML=[...e.target.files].map(f=>`<li>${escapeHtml(f.name)} · ${formatSize(f.size)}</li>`).join('')};function formatSize(n){return n>1048576?(n/1048576).toFixed(1)+' Mo':Math.ceil(n/1024)+' Ko'}function escapeHtml(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
document.querySelector('#downloadBackup').onclick=()=>{save();const payload={titre:config?.full||'Copie de sécurité — projet CARDIE-SEPIA',mode,date:new Date().toISOString(),dossier:data(),pieces_jointes:[...document.querySelector('#attachments').files].map(f=>({nom:f.name,taille:f.size}))};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`dossier-cardie-sepia-${mode||'projet'}-sauvegarde.json`;a.click();URL.revokeObjectURL(a.href)};
const pdfLabels={typologie:'Typologie du projet',recherche:'Projet adossé à la recherche',recherche_details:'Laboratoire, chercheur ou travaux de recherche',structure:'Structure déposante',etablissement:'École ou établissement',uai:'UAI',type_etab:'Typologie de l’établissement',ville:'Ville',statut_etablissement:'Statut de l’établissement',education_prioritaire:'Éducation prioritaire',inspecteur:'IEN / IA-IPR référent',intitule:'Intitulé de l’action',genese:'Diagnostic de départ',evaluations_nationales:'Lien avec les évaluations nationales',auto_evaluation:'Lien avec l’auto-évaluation ou l’évaluation externe',projet_etab:'Inscription dans le projet d’établissement',etat_projet:'État du projet',objectifs:'Objectifs pédagogiques',plan_action:'Plan d’action',leviers:'Principaux leviers',freins:'Principaux freins',pilotage:'Instance de pilotage prévue',pilotage_details:'Instance et modalités',formation:'Formations nécessaires',formation_details:'Thématiques de formation',temporalite:'Début et durée du projet',pluriannuel:'Inscription dans un plan pluriannuel',pluriannuel_details:'Temporalité prévue',eleves_nombre:'Nombre d’élèves',eleves_niveaux:'Niveaux des élèves',enseignants_nombre:'Nombre d’enseignants',enseignants_disciplines:'Disciplines',autres_nombre:'Nombre d’autres personnels',autres_fonctions:'Fonctions des autres personnels',familles:'Familles associées',familles_details:'Modalités et rôle des familles',dispositifs:'Dispositifs, contrats ou démarches',autre_dispositif:'Autre dispositif',effets_eleves:'Effets recherchés sur les élèves',indicateurs_eleves:'Indicateurs concernant les élèves',effets_enseignants:'Effets sur les pratiques enseignantes',indicateurs_enseignants:'Indicateurs concernant les enseignants',effets_etab:'Effets sur l’établissement',indicateurs_etab:'Indicateurs concernant l’établissement',accompagnement:'Besoins d’accompagnement',financement:'Financement existant',financement_details:'Précisions sur le financement',hse:'Besoin de valorisation en HSE',hse_details:'Usage prévu des HSE'};
function valueText(v){if(Array.isArray(v))return v.map(x=>typeof x==='object'?Object.values(x).filter(Boolean).join(' · '):x).filter(Boolean).join(' ; ');return String(v??'').trim()}
function shorten(text,max=110){text=valueText(text);return text.length>max?text.slice(0,max-1)+'…':text}
function fitText(font,text,maxWidth,maxSize=7,minSize=4){let size=maxSize;while(size>minSize&&font.widthOfTextAtSize(text,size)>maxWidth)size-=.25;return size}
function drawLine(page,font,text,x,y,width,size=7){text=shorten(text);if(!text)return;page.drawText(text,{x,y,size:fitText(font,text,width,size),font,color:PDFLib.rgb(.12,.12,.12),maxWidth:width})}
function tick(page,x,y){page.drawText('X',{x,y,size:8,color:PDFLib.rgb(.1,.1,.1)})}
function yesNo(page,value,yesX,noX,y){if(value==='Oui')tick(page,yesX,y);if(value==='Non')tick(page,noX,y)}
function drawOfficialForm(pdf,font,d){const p2=pdf.getPage(1),p3=pdf.getPage(2),p4=pdf.getPage(3),p5=pdf.getPage(4);
 if(d.typologie==='Projet innovant')tick(p2,132,754);else if(d.typologie)tick(p2,316,754);yesNo(p2,d.recherche,159,426,699);drawLine(p2,font,d.recherche_details,40,650,525);if(d.structure==='Corps d’inspection')tick(p2,67,385);if(d.structure==='Établissement scolaire')tick(p2,67,339);drawLine(p2,font,d.inspecteur,38,205,360);drawLine(p2,font,d.uai,430,205,120);drawLine(p2,font,d.type_etab,42,263,95);drawLine(p2,font,d.etablissement,143,263,245);drawLine(p2,font,d.ville,400,263,80);if(d.education_prioritaire==='Oui')tick(p2,501,263);if(d.education_prioritaire==='Non')tick(p2,501,248);if(mode==='hors-appel'&&d.statut_etablissement){if(d.statut_etablissement==='Public')tick(p2,552,263);else tick(p2,552,248)}drawLine(p2,font,d.intitule,38,115,525,8);
 drawLine(p3,font,d.genese,39,735,522);yesNo(p3,d.evaluations_nationales,159,426,700);yesNo(p3,d.auto_evaluation,159,426,654);yesNo(p3,d.projet_etab,159,426,609);if(d.etat_projet==='Préexistant')tick(p3,159,566);if(d.etat_projet==='Nouveau')tick(p3,426,566);drawLine(p3,font,d.objectifs,39,460,522);drawLine(p3,font,d.plan_action,39,415,522);drawLine(p3,font,d.leviers,39,370,522);drawLine(p3,font,d.freins,39,325,522);yesNo(p3,d.pilotage,159,426,289);drawLine(p3,font,d.pilotage_details,68,260,493);yesNo(p3,d.formation,159,426,220);drawLine(p3,font,d.formation_details,68,190,493);drawLine(p3,font,d.temporalite,68,100,493);yesNo(p3,d.pluriannuel,159,426,65);
 const porteur=(d.porteurs||[])[0]||{};drawLine(p4,font,porteur.nom,141,661,105);drawLine(p4,font,porteur.prenom,250,661,105);drawLine(p4,font,porteur.fonction,359,661,200);drawLine(p4,font,d.eleves_nombre,179,590,90);drawLine(p4,font,d.eleves_niveaux,367,590,180);drawLine(p4,font,d.enseignants_nombre,179,551,90);drawLine(p4,font,d.enseignants_disciplines,367,551,180);drawLine(p4,font,d.autres_nombre,179,513,90);drawLine(p4,font,d.autres_fonctions,367,513,180);yesNo(p4,d.familles,159,426,486);drawLine(p4,font,d.familles_details,68,451,493);const partenaire=(d.partenaires||[])[0]||{};drawLine(p4,font,partenaire.entite,70,363,245);drawLine(p4,font,partenaire.role,319,363,240);const dev=[].concat(d.dispositifs||[]);if(dev.includes('Cité éducative'))tick(p4,69,302);if(dev.includes('TER'))tick(p4,307,302);if(dev.includes('CLA'))tick(p4,69,286);if(dev.includes('OTA 62'))tick(p4,307,286);drawLine(p4,font,d.autre_dispositif,90,268,200);
 drawLine(p5,font,d.effets_eleves,39,740,522);if(valueText(d.indicateurs_eleves))tick(p5,159,695);drawLine(p5,font,d.indicateurs_eleves,68,660,493);drawLine(p5,font,d.effets_enseignants,39,560,522);if(valueText(d.indicateurs_enseignants))tick(p5,159,515);drawLine(p5,font,d.indicateurs_enseignants,68,490,493);drawLine(p5,font,d.effets_etab,39,380,522);if(valueText(d.indicateurs_etab))tick(p5,159,335);drawLine(p5,font,d.indicateurs_etab,68,310,493);drawLine(p5,font,d.accompagnement,68,210,493);if(mode==='public'){yesNo(p5,d.financement,159,426,168);drawLine(p5,font,d.financement_details,68,135,493);yesNo(p5,d.hse,159,426,107);drawLine(p5,font,d.hse_details,68,58,493)} }
function wrap(font,text,size,width){const words=valueText(text).split(/\s+/);const lines=[];let line='';for(const word of words){const test=line?line+' '+word:word;if(font.widthOfTextAtSize(test,size)<=width)line=test;else{if(line)lines.push(line);line=word}}if(line)lines.push(line);return lines}
function addAnnex(pdf,font,bold,d){const entries=[];Object.entries(d).forEach(([k,v])=>{const text=valueText(v);if(text)entries.push([pdfLabels[k]||k.replaceAll('_',' '),text])});let page,y;const newPage=()=>{page=pdf.addPage([595.28,841.89]);page.drawRectangle({x:0,y:785,width:595.28,height:56,color:PDFLib.rgb(.35,.16,.45)});page.drawText('CARDIE-SEPIA — Réponses complètes',{x:38,y:808,size:15,font:bold,color:PDFLib.rgb(1,1,1)});page.drawText(config.full,{x:38,y:791,size:9,font,color:PDFLib.rgb(1,1,1)});y=758};newPage();for(const [label,text] of entries){const lines=wrap(font,text,8.5,519);const needed=18+lines.length*11;if(y-needed<45)newPage();page.drawText(label,{x:38,y,size:9,font:bold,color:PDFLib.rgb(.35,.16,.45)});y-=13;for(const line of lines){page.drawText(line,{x:38,y,size:8.5,font,color:PDFLib.rgb(.1,.1,.1)});y-=11}y-=9}return pdf}
async function exportFilledPdf(){const btn=document.querySelector('#printPdf'),old=btn.textContent;try{btn.disabled=true;btn.textContent='Création du PDF…';save();const bytes=await fetch(config.pdf).then(r=>{if(!r.ok)throw new Error('Modèle PDF indisponible');return r.arrayBuffer()});const pdf=await PDFLib.PDFDocument.load(bytes);const font=await pdf.embedFont(PDFLib.StandardFonts.Helvetica),bold=await pdf.embedFont(PDFLib.StandardFonts.HelveticaBold);const d=data();drawOfficialForm(pdf,font,d);addAnnex(pdf,font,bold,d);pdf.setTitle(config.full+' — dossier complété');pdf.setSubject('Dossier CARDIE-SEPIA complété depuis le formulaire en ligne');const out=await pdf.save();const blob=new Blob([out],{type:'application/pdf'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`dossier-cardie-sepia-${mode}-complete.pdf`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1500)}catch(e){console.error(e);alert('Le PDF n’a pas pu être créé. Vérifiez votre connexion puis réessayez.')}finally{btn.disabled=false;btn.textContent=old}}
document.querySelector('#printPdf').onclick=exportFilledPdf;document.querySelector('#submitDemo').onclick=()=>{save();document.querySelector('#successDialog').showModal()};document.querySelector('#closeDialog').onclick=()=>document.querySelector('#successDialog').close();
function registerWebMCP(){const ctx=document.modelContext;if(!ctx?.registerTool)return;const control=new AbortController();const register=t=>Promise.resolve(ctx.registerTool(t,{signal:control.signal})).catch(()=>{});register({name:'read_project_draft',title:'Lire le brouillon',description:'Lire les réponses actuellement enregistrées dans le démonstrateur CARDIE-SEPIA.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:()=>({step:current+1,stepTitle:steps[current].dataset.title,fields:data()})});register({name:'navigate_project_form',title:'Ouvrir une étape',description:'Afficher une étape numérotée de 1 à 7 du formulaire de projet CARDIE-SEPIA.',inputSchema:{type:'object',properties:{step:{type:'integer',minimum:1,maximum:7}},required:['step'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:({step})=>{if(!Number.isInteger(step)||step<1||step>7)throw new Error('Étape invalide');go(step-1);return{step,stepTitle:steps[step-1].dataset.title}}});register({name:'save_project_draft',title:'Enregistrer le brouillon',description:'Enregistrer localement les réponses actuelles du formulaire sur cet appareil.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:()=>{save();return{saved:true,savedAt:new Date().toISOString()}}})}
if(config){restore();go(0);updateConditionals();registerWebMCP()}
