const params=new URLSearchParams(location.search);const mode=params.get('mode')||document.body.dataset.defaultMode||null;const configs={public:{kicker:'Appel à projets 2026–2027',main:'Établissements publics',full:'Formulaire d’appel à projets pour établissements publics'},prive:{kicker:'Appel à projets 2026–2027',main:'Établissements privés',full:'Formulaire d’appel à projets pour établissements privés'},'hors-appel':{kicker:'Dépôt permanent',main:'Projet hors appel à projets',full:'Formulaire de dépôt de projet hors appel à projets'}};
const config=configs[mode];document.querySelector('#modelPicker').hidden=!!config;document.querySelector('#formApp').hidden=!config;if(!config){document.title='Formulaires de dépôt — CARDIE-SEPIA Lille'}else{document.querySelector('#formKicker').textContent=config.kicker;document.querySelector('#formMainTitle').textContent=config.main;document.querySelector('#formFullTitle').textContent=config.full;document.title=config.full+' — CARDIE-SEPIA Lille';document.body.dataset.mode=mode;if(mode==='hors-appel')document.querySelectorAll('.hors-only').forEach(x=>x.style.display='block');if(mode!=='public')document.querySelectorAll('.public-only').forEach(x=>x.hidden=true)}
const form=document.querySelector('#projectForm');const steps=[...document.querySelectorAll('.step')];let current=0;const key=`cardie-sepia-demo-v2-${mode||'accueil'}`;
const nav=document.querySelector('#stepNav');steps.forEach((s,i)=>{const b=document.createElement('button');b.type='button';b.innerHTML=`<span>${i+1}</span>${s.dataset.title}`;b.onclick=()=>go(i);nav.appendChild(b)});
function go(i,validate=false){if(validate&&!validateStep())return;current=Math.max(0,Math.min(i,steps.length-1));steps.forEach((s,n)=>s.classList.toggle('active',n===current));[...nav.children].forEach((b,n)=>b.classList.toggle('active',n===current));document.querySelector('#stepLabel').textContent=`Étape ${current+1} sur ${steps.length}`;document.querySelector('#stepTitle').textContent=steps[current].dataset.title;document.querySelector('#progressBar').style.width=`${(current+1)/steps.length*100}%`;document.querySelector('#prevBtn').disabled=current===0;document.querySelector('#nextBtn').hidden=current===steps.length-1;window.scrollTo({top:0,behavior:'smooth'})}
function validateStep(){let ok=true;steps[current].querySelectorAll('[required]').forEach(el=>{const valid=el.type==='radio'?[...steps[current].querySelectorAll(`[name="${el.name}"]`)].some(x=>x.checked):el.value.trim();el.classList.toggle('invalid',!valid);if(!valid)ok=false});if(!ok){steps[current].querySelector('.invalid,[required]')?.focus();return false}return true}
document.querySelector('#nextBtn').onclick=()=>{save();go(current+1,true)};document.querySelector('#prevBtn').onclick=()=>go(current-1);
function data(){const out={};new FormData(form).forEach((v,k)=>{if(v instanceof File)return;if(out[k])out[k]=[].concat(out[k],v);else out[k]=v});document.querySelectorAll('.repeater').forEach(r=>{out[r.dataset.name]=[...r.querySelectorAll('.repeat-row')].map(row=>Object.fromEntries([...row.querySelectorAll('[data-field]')].map(x=>[x.dataset.field,x.value]))) });return out}
function save(){localStorage.setItem(key,JSON.stringify({savedAt:new Date().toISOString(),fields:data()}));const s=document.querySelector('#saveState');s.innerHTML='<span></span>Brouillon enregistré à '+new Date().toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'})}
function restore(){try{const saved=JSON.parse(localStorage.getItem(key)||'null');if(!saved)return;Object.entries(saved.fields||{}).forEach(([k,v])=>{if(['porteurs','partenaires'].includes(k)){restoreRepeater(k,v);return}const els=[...form.querySelectorAll(`[name="${CSS.escape(k)}"]`)];els.forEach(el=>{if(el.type==='radio'||el.type==='checkbox')el.checked=[].concat(v).includes(el.value);else el.value=Array.isArray(v)?v[0]:v})});updateConditionals()}catch(e){console.warn('Brouillon illisible',e)}}
function restoreRepeater(name,rows){const rep=document.querySelector(`.repeater[data-name="${name}"]`);if(!rep||!rows?.length)return;const box=rep.querySelector('.repeat-items'),tpl=box.firstElementChild.cloneNode(true);box.innerHTML='';rows.forEach(values=>{const row=tpl.cloneNode(true);row.querySelectorAll('[data-field]').forEach(x=>x.value=values[x.dataset.field]||'');box.appendChild(row)})}
function updateConditionals(){document.querySelectorAll('.conditional').forEach(c=>{const [name,value]=c.dataset.show.split(':');const selected=form.querySelector(`[name="${name}"]:checked`);c.classList.toggle('visible',selected?.value===value)})}
form.addEventListener('input',()=>{updateConditionals();clearTimeout(window.saveTimer);window.saveTimer=setTimeout(save,350)});form.addEventListener('change',()=>{updateConditionals();save()});
document.querySelectorAll('.repeater').forEach(rep=>{rep.querySelector('.add').onclick=()=>{const row=rep.querySelector('.repeat-row').cloneNode(true);row.querySelectorAll('input').forEach(x=>x.value='');rep.querySelector('.repeat-items').appendChild(row);save()};rep.addEventListener('click',e=>{if(!e.target.classList.contains('remove'))return;const rows=rep.querySelectorAll('.repeat-row');if(rows.length>1)e.target.closest('.repeat-row').remove();else e.target.closest('.repeat-row').querySelectorAll('input').forEach(x=>x.value='');save()})});
document.querySelector('#attachments').onchange=e=>{document.querySelector('#fileList').innerHTML=[...e.target.files].map(f=>`<li>${escapeHtml(f.name)} · ${formatSize(f.size)}</li>`).join('')};function formatSize(n){return n>1048576?(n/1048576).toFixed(1)+' Mo':Math.ceil(n/1024)+' Ko'}function escapeHtml(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
document.querySelector('#downloadBackup').onclick=()=>{save();const payload={titre:config?.full||'Copie de sécurité — projet CARDIE-SEPIA',mode,date:new Date().toISOString(),dossier:data(),pieces_jointes:[...document.querySelector('#attachments').files].map(f=>({nom:f.name,taille:f.size}))};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`dossier-cardie-sepia-${mode||'projet'}-sauvegarde.json`;a.click();URL.revokeObjectURL(a.href)};
document.querySelector('#printPdf').onclick=()=>window.print();document.querySelector('#submitDemo').onclick=()=>{save();document.querySelector('#successDialog').showModal()};document.querySelector('#closeDialog').onclick=()=>document.querySelector('#successDialog').close();
function registerWebMCP(){const ctx=document.modelContext;if(!ctx?.registerTool)return;const control=new AbortController();const register=t=>Promise.resolve(ctx.registerTool(t,{signal:control.signal})).catch(()=>{});register({name:'read_project_draft',title:'Lire le brouillon',description:'Lire les réponses actuellement enregistrées dans le démonstrateur CARDIE-SEPIA.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:()=>({step:current+1,stepTitle:steps[current].dataset.title,fields:data()})});register({name:'navigate_project_form',title:'Ouvrir une étape',description:'Afficher une étape numérotée de 1 à 7 du formulaire de projet CARDIE-SEPIA.',inputSchema:{type:'object',properties:{step:{type:'integer',minimum:1,maximum:7}},required:['step'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:({step})=>{if(!Number.isInteger(step)||step<1||step>7)throw new Error('Étape invalide');go(step-1);return{step,stepTitle:steps[step-1].dataset.title}}});register({name:'save_project_draft',title:'Enregistrer le brouillon',description:'Enregistrer localement les réponses actuelles du formulaire sur cet appareil.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:()=>{save();return{saved:true,savedAt:new Date().toISOString()}}})}
if(config){restore();go(0);updateConditionals();registerWebMCP()}